# Generated by Django 5.0 on 2024-01-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
