# Generated by Django 5.0 on 2024-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='previewLink',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='books',
            name='publishedDate',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
