# Generated by Django 5.0 on 2024-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
