# Generated by Django 5.0 on 2024-01-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='country',
            new_name='country_id',
        ),
    ]
