# Generated by Django 5.0 on 2024-01-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_review_summary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
