# Generated by Django 5.0 on 2024-01-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_books_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='books',
            name='original_language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
