# Generated by Django 5.0 on 2024-01-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_faq'),
    ]

    operations = [
    ]
