# Generated by Django 5.0 on 2024-01-05 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_books_language_books_original_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='country',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='authors',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='authors',
            name='date_of_death',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
