# Generated by Django 5.0 on 2024-01-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_authors_country_authors_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='date_of_birth',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='authors',
            name='date_of_death',
            field=models.CharField(default=''),
        ),
    ]
