# Generated by Django 5.0 on 2024-01-01 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_auto_20240101_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
