# Generated by Django 5.0 on 2024-01-01 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shopapp.authors'),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default='Description is not available'),
        ),
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.CharField(default='default.jpg', max_length=35),
        ),
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='books',
            name='title',
            field=models.CharField(default='Book', max_length=100),
        ),
    ]
